Repository kimyoo04/seoul-competition-frontend, pull requests merged in 2023-05, with the labels that each got.

#63 Feature/유저폼 구현
  pages/tmp/index.tsx
  src/components/UserForm/index.tsx
  src/components/UserForm/userFormData.ts
  src/type/userForm.ts
  styles/globals.css
Labels: Feature

#67 Feature/search와 filter 기능 통합
  pages/_app.tsx
  pages/search/index.tsx
  src/api/fetchSearch.ts
  src/components/FilterToggle/index.tsx
  src/components/LocationMap/index.tsx
  src/components/SearchLink/index.tsx
  src/components/Sidebar/CalendarFilter/index.tsx
  src/components/Sidebar/PriceFilter/index.tsx
  src/components/Sidebar/SearchBar/index.tsx
  src/components/Sidebar/SearchCategory/index.tsx
  src/components/Sidebar/SearchKeywordsModal/SearchKeywordsItem/SearchKeywordsHeader.tsx
  src/components/Sidebar/SearchKeywordsModal/SearchKeywordsItem/SearchKeywordsItem.tsx
  src/components/Sidebar/SearchKeywordsModal/index.tsx
  src/components/Sidebar/StatusFilter/index.tsx
  src/components/Sidebar/index.tsx
  src/features/filter/filterSlice.ts
  src/scenes/Educations/index.tsx
  src/scenes/Home/CTABtn/index.tsx
  src/scenes/Home/index.tsx
  src/scenes/Posts/index.tsx
  src/scenes/Search/ChooseCategory/ChooseButton.tsx
  src/scenes/Search/ChooseCategory/index.tsx
  src/scenes/Search/SearchRanking/index.tsx
  src/scenes/Search/SearchResult/SearchResultItem/header.tsx
  src/scenes/Search/SearchResult/index.tsx
  src/scenes/Search/index.tsx
  src/toolkit/store.ts
  src/type/filter.ts
Labels: Bug, Feature, Refactor, Style

#68 Feature/search와 filter 기능 통합
  src/api/fetchEducations.ts
  src/api/fetchPosts.ts
  src/components/Search/SearchHeader.tsx
  src/components/Search/SearchMore.tsx
  src/layouts/Header/HeaderItem/NavLinks.tsx
  src/layouts/Header/index.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Educations/index.tsx
  src/scenes/Posts/PostList/index.tsx
  src/scenes/Posts/index.tsx
  src/type/education.ts
  src/type/educationDetail.ts
  src/type/posts.ts
Labels: Bug, Feature, Refactor

#69 Feature/자유게시판 게시글cud
  pages/posts/new/index.tsx
  src/api/createPost.ts
  src/scenes/Posts/AddPost/index.tsx
  src/scenes/Posts/PostForm/index.tsx
  src/scenes/Posts/PostItem/CreateButton.tsx
  src/scenes/Posts/PostItem/index.tsx
  src/type/postForm.ts
Labels: Feature

#70 Fix/자유게시판 게시글cud
  src/api/createPost.ts
  src/scenes/Posts/AddPost/index.tsx
  src/scenes/Posts/PostForm/index.tsx
  src/type/postForm.ts
Labels: Bug

#71 Feature/side bar filter UI 구현
  package-lock.json
  package.json
  pages/_app.tsx
  src/api/fetchEducations.ts
  src/components/Sidebar/CalendarFilter/index.tsx
  src/components/Sidebar/PriceFilter/index.tsx
  src/components/Sidebar/SearchCategory/index.tsx
  src/components/Sidebar/SearchKeywordsModal/index.tsx
  src/components/Sidebar/StatusFilter/index.tsx
  src/components/Sidebar/index.tsx
  src/features/filter/filterSlice.ts
  src/type/filter.ts
  src/type/search.ts
  src/util/dateTime.ts
  styles/filter.css
Labels: Feature, Design

#73 Feature/유저폼 구현
  src/api/user/createUser.tsx
  src/components/UserForm/index.tsx
  src/components/UserForm/userFormData.ts
  src/type/userForm.ts
Labels: Feature, Design

#74 Feature/api_폴더_정리
  src/api/educations/readEducationDetail.ts
  src/api/educations/readEducations.ts
  src/scenes/Educations/EducationDetail/index.tsx
  src/scenes/Educations/EducationList/index.tsx
Labels: Other

#76 feature/댓글_컴포넌트_리펙토링_시작
  src/components/Comment/CommentInput.tsx
  src/components/Comment/CommentUpDelButtons.tsx
  src/components/Comment/Comments.tsx
  src/scenes/Posts/postDetail/index.tsx
Labels: Refactor

#78 Feature/댓글 컴포넌트 리펙토링
  src/api/educations/readEducations.ts
  src/components/Comment/CommentInput.tsx
  src/components/Comment/CommentUpDelButtons.tsx
  src/components/Comment/Comments.tsx
  src/scenes/Educations/EducationItem/index.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Posts/postDetail/PostDetailItem/Content.tsx
  src/scenes/Posts/postDetail/PostDetailItem/Header.tsx
  src/scenes/Posts/postDetail/PostDetailItem/UpDelButtons.tsx
  src/scenes/Posts/postDetail/index.tsx
  src/type/comments.ts
  src/type/education.ts
  src/type/educationDetail.ts
  src/type/educations.ts
  src/type/postDetail.ts
  src/type/posts.ts
  styles/button.css
Labels: Refactor

#81 Feature/교육정보 댓글 구현
  src/api/comment/createComment.ts
  src/api/comment/deleteComment.ts
  src/api/comment/matchCheckComment.ts
  src/api/comment/updateComment.ts
  src/api/review/createReview.ts
  src/api/review/deleteReview.ts
  src/api/review/matchCheckReview.ts
  src/api/review/updateReview.ts
  src/components/Alert/index.tsx
  src/components/Comments/CommentInput.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/index.tsx
  src/layouts/DetailPageLayout.tsx
  src/scenes/Educations/EducationItem/index.tsx
  src/type/commentOrReview.ts
  src/type/comments.ts
  src/type/educationDetail.ts
  src/type/educations.ts
  src/type/filter.ts
  src/type/postDetail.ts
  src/type/posts.ts
Labels: Feature, Refactor

#82 Feature/게시글 삭제 버튼 구현
  src/api/posts/deletePostDetail.ts
  src/api/posts/matchCheckPostDetail.ts
  src/api/posts/updatePostDetail.ts
  src/scenes/Posts/EditPost/PostUpdatePwd.tsx
  src/scenes/Posts/postDetail/PostDetailItem/UpDelButtons.tsx
  src/type/posts.ts
Labels: Feature, Refactor

#83 Feature/유저폼 적용
  src/api/educations/readEducationDetail.ts
  src/api/posts/readPostDetail.ts
  src/api/user/createUser.tsx
  src/components/UserForm/index.tsx
  src/features/userForm/userFormSlice.ts
  src/scenes/Educations/EducationDetail/index.tsx
  src/scenes/Posts/postDetail/index.tsx
  src/toolkit/store.ts
  src/type/educationDetail.ts
  src/type/postDetail.ts
  src/type/userForm.ts
Labels: Feature, Refactor, Design

#84 Feature/유사 게시물 추천 UI 구현
  src/api/educations/readEducations.ts
  src/api/similar/readSimilarEducationsById.ts
  src/api/similar/readSimilarEducationsByKeyword.ts
  src/components/SimilarEducationDetail/index.tsx
  src/components/SimilarEducationList/index.tsx
  src/scenes/Educations/EducationDetail/index.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Posts/postDetail/index.tsx
  src/type/search.ts
Labels: Feature

#86 Feature/자유게시판 게시글cud
  src/api/posts/updatePostDetail.ts
  src/scenes/Posts/AddPost/index.tsx
  src/scenes/Posts/EditPost/PostUpdatePwd.tsx
  src/scenes/Posts/EditPost/index.tsx
  src/scenes/Posts/postDetail/PostDetailItem/UpDelButtons.tsx
Labels: Feature

#89 Feature/자유게시판 게시글cud
  src/api/posts/createPostDetail.ts
  src/scenes/Posts/AddPost/index.tsx
  src/scenes/Posts/EditPost/PostUpdatePwd.tsx
  src/scenes/Posts/EditPost/index.tsx
Labels: Bug, Style

#91 Feature/react content loader 적용
  package-lock.json
  package.json
  src/components/Sidebar/index.tsx
  src/layouts/Header/HeaderItem/NavLinks.tsx
  src/scenes/Educations/EducationList/EducationListLoader.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Posts/PostList/PostListLoader.tsx
  src/scenes/Posts/PostList/index.tsx
  tailwind.config.js
Labels: Bug, Feature, Design

#92 Feature/total counts를 sidebar에 적용
  src/components/Sidebar/CalendarFilter/index.tsx
  src/components/Sidebar/PriceFilter/index.tsx
  src/components/Sidebar/SearchBar/index.tsx
  src/components/Sidebar/SearchCategory/index.tsx
  src/components/Sidebar/SearchKeywordsModal/SearchKeywordsItem/SearchKeywordsHeader.tsx
  src/components/Sidebar/SearchKeywordsModal/SearchKeywordsItem/SearchKeywordsItem.tsx
  src/components/Sidebar/ShowTotalCounts/index.tsx
  src/components/Sidebar/StatusFilter/index.tsx
  src/components/Sidebar/index.tsx
  src/features/filter/filterSlice.ts
  src/scenes/Educations/EducationList/EducationListLoader.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Posts/PostList/PostListLoader.tsx
  src/scenes/Posts/PostList/index.tsx
  src/type/educations.ts
  src/type/filter.ts
  src/type/posts.ts
Labels: Feature

#94 Feature/subset 폰트 적용 및 코드 리펙토링
  .prettierrc.js
  public/data/educationData.ts
  public/data/postData.ts
  public/fonts/NotoSansKR/NotoSansKR-Bold.otf
  public/fonts/NotoSansKR/NotoSansKR-Bold.woff
  public/fonts/NotoSansKR/NotoSansKR-Bold.woff2
  public/fonts/NotoSansKR/NotoSansKR-Light.otf
  public/fonts/NotoSansKR/NotoSansKR-Light.woff
  public/fonts/NotoSansKR/NotoSansKR-Light.woff2
  public/fonts/NotoSansKR/NotoSansKR-Medium.otf
  public/fonts/NotoSansKR/NotoSansKR-Medium.woff
  public/fonts/NotoSansKR/NotoSansKR-Medium.woff2
  public/fonts/NotoSansKR/NotoSansKR-Regular.otf
  public/fonts/NotoSansKR/NotoSansKR-Regular.woff
  public/fonts/NotoSansKR/NotoSansKR-Regular.woff2
  src/constants/.gitkeep
  src/constants/home/contents.ts
  src/layouts/Footer/.gitkeep
  src/scenes/Home/index.tsx
  styles/globals.css
Labels: Other, Refactor

#97 Feature/fixed 버튼 위치 조정 및 chat css 조정
  src/components/Chat/ChatButton/index.tsx
  src/components/Chat/ChatHeader/index.tsx
  src/components/Chat/ChatInput/index.tsx
  src/components/FilterToggle/index.tsx
  src/components/ScrollButton/index.tsx
  src/scenes/Posts/CreateButton/index.tsx
  src/scenes/Posts/index.tsx
  src/type/chat.ts
  styles/chat.css
Labels: Feature, Design

#98 Feature/자유게시판 게시글 댓글
  src/api/comment/updateComment.ts
  src/components/Comments/CommentDelButton.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentUpDelButtons.tsx
  src/components/Comments/CommentUpdatePwd.tsx
  src/features/comment/commentSlice.ts
  src/toolkit/store.ts
  src/type/comment.ts
  src/type/commentOrReview.ts
Labels: Feature, Question

#99 Feature/댓글 curd 마무리
  src/api/comment/createComment.ts
  src/api/comment/deleteComment.ts
  src/api/comment/updateComment.ts
  src/api/review/createReview.ts
  src/api/review/deleteReview.ts
  src/api/review/updateReview.ts
  src/components/Comments/CommentDelButton.tsx
  src/components/Comments/CommentInput.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentUpdatePwd.tsx
  src/features/comment/commentSlice.ts
  src/scenes/Posts/AddPost/index.tsx
  src/scenes/Posts/EditPost/PostUpdatePwd.tsx
  src/scenes/Posts/EditPost/index.tsx
  src/type/comment.ts
Labels: Refactor, Design

#100 Feature/유사교육정보 구현
  src/api/similar/readSimilarEducationsById.ts
  src/api/similar/readSimilarEducationsByKeyword.ts
  src/components/SimilarEducationList/index.tsx
  src/layouts/Header/MobileHeader/menu.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Home/ContentItem/index.tsx
Labels: Feature, Design

#101 Feature/educations UI 개선
  src/components/Chat/ChatButton/index.tsx
  src/components/FilterToggle/index.tsx
  src/components/ScrollButton/index.tsx
  src/scenes/Educations/EducationItem/index.tsx
  src/scenes/Educations/EducationList/index.tsx
Labels: Refactor, Design

#102 Feature/docker image 최적화 및 배포준비
  .dockerignore
  Dockerfile
  Dockerfile.dev
  Dockerfile.prod
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  public/fonts/NotoSansKR/NotoSansKR-Bold.otf
  public/fonts/NotoSansKR/NotoSansKR-Bold.woff
  public/fonts/NotoSansKR/NotoSansKR-Bold.woff2
  public/fonts/NotoSansKR/NotoSansKR-Light.otf
  public/fonts/NotoSansKR/NotoSansKR-Light.woff
  public/fonts/NotoSansKR/NotoSansKR-Light.woff2
  public/fonts/NotoSansKR/NotoSansKR-Medium.otf
  public/fonts/NotoSansKR/NotoSansKR-Medium.woff
  public/fonts/NotoSansKR/NotoSansKR-Medium.woff2
  public/fonts/NotoSansKR/NotoSansKR-Regular.otf
  public/fonts/NotoSansKR/NotoSansKR-Regular.woff
  public/fonts/NotoSansKR/NotoSansKR-Regular.woff2
  public/fonts/NotoSansKR/OFL.txt
  src/api/axiosInstance.ts
  src/components/Chat/ChatMessage/index.tsx
  src/util/dateTime.ts
  src/util/localImageLoader.ts
  styles/globals.css
Labels: Bug, Feature, Refactor, Style

#106 Feature/웹사이트 UI 섬세하게 수정
  Dockerfile
  next.config.js
  public/images/chatbot.png
  src/api/educations/readEducations.ts
  src/api/posts/readPosts.ts
  src/components/Chat/ChatButton/index.tsx
  src/components/Chat/ChatMessage/index.tsx
  src/components/Comments/CommentDelButton.tsx
  src/components/Comments/CommentInput.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentUpdatePwd.tsx
  src/components/FilterToggle/index.tsx
  src/components/ScrollButton/index.tsx
  src/components/Search/SearchNotFound.tsx
  src/components/Sidebar/SearchBar/index.tsx
  src/components/Sidebar/index.tsx
  src/components/SimilarEducationDetail/index.tsx
  src/components/SimilarEducationList/index.tsx
  src/features/chat/chatSlice.ts
  src/features/filter/filterSlice.ts
  src/features/search/searchSlice.ts
  src/layouts/DetailPageLayout.tsx
  src/layouts/Header/MobileHeader/index.tsx
  src/layouts/MainLayout.tsx
  src/layouts/OnePageLayout.tsx
  src/scenes/Educations/EducationDetail/EducationDetailItem/Header.tsx
  src/scenes/Educations/EducationDetail/EducationDetailItem/content.tsx
  src/scenes/Educations/EducationDetail/index.tsx
  src/scenes/Educations/EducationItem/index.tsx
  src/scenes/Educations/EducationList/EducationListLoader.tsx
  src/scenes/Educations/EducationList/index.tsx
  src/scenes/Educations/index.tsx
  src/scenes/Posts/CreateButton/index.tsx
  src/scenes/Posts/PostItem/index.tsx
  src/scenes/Posts/PostList/index.tsx
  src/scenes/Posts/index.tsx
  src/util/dateTime.ts
  src/util/localImageLoader.ts
  src/util/truncateString.ts
  styles/globals.css
Labels: Bug, Feature, Refactor, Design

#109 Feature/챗봇답변 피드백 구현
  src/api/chat/putFeedback.ts
  src/components/Chat/ChatInput/index.tsx
  src/components/Chat/ChatMessage/index.tsx
  src/features/chat/chatSlice.ts
  src/type/chat.ts
  styles/chat.css
Labels: Feature, Design

#111 Feature/자유게시판 게시글 댓글
  package-lock.json
  package.json
  pages/index.tsx
  public/data/rankingData.ts
  src/api/rank/readEducationInterestRank.ts
  src/api/rank/readEducationRank.ts
  src/api/rank/readKeywordAgeRank.ts
  src/api/rank/readKeywordRank.ts
  src/api/rank/readPostRank.ts
  src/components/Comments/CommentItem.tsx
  src/components/Rank/DropdownItems/AgeToggle.tsx
  src/components/Rank/DropdownItems/AgeToggleList.tsx
  src/components/Rank/DropdownItems/InterestToggle.tsx
  src/components/Rank/DropdownItems/InterestToggleList.tsx
  src/components/Rank/EducationRank/EducationRankItem/index.tsx
  src/components/Rank/EducationRank/EducationRankList/index.tsx
  src/components/Rank/EducationRank/index.tsx
  src/components/Rank/KewordRank/PieChart/index.tsx
  src/components/Rank/KewordRank/index.tsx
  src/components/Rank/PostRank/PostRankItem/index.tsx
  src/components/Rank/PostRank/PostRankList/index.tsx
  src/components/Rank/PostRank/index.tsx
  src/components/Rank/SearchKeywordRank/SearchKeywordRankItem/index.tsx
  src/components/Rank/SearchKeywordRank/SearchKeywordRankList/index.tsx
  src/components/Rank/SearchKeywordRank/index.tsx
  src/components/Rank/index.tsx
  src/features/rank/ageSlice.ts
  src/features/rank/interestSlice.ts
  src/scenes/Home/index.tsx
  src/scenes/Posts/PostItem/index.tsx
  src/toolkit/store.ts
  src/type/rank.ts
Labels: Bug, Feature, Question, Style

#112 Hotfix/user의 age 값 조정
  src/api/rank/readEducationInterestRank.ts
  src/api/rank/readEducationRank.ts
  src/api/rank/readKeywordAgeRank.ts
  src/api/rank/readKeywordRank.ts
  src/api/rank/readPostRank.ts
  src/api/user/createUser.tsx
  src/components/Rank/DropdownItems/AgeDropDown.tsx
  src/components/Rank/DropdownItems/AgeToggle.tsx
  src/components/Rank/DropdownItems/AgeToggleList.tsx
  src/components/Rank/DropdownItems/InterestDropDown.tsx
  src/components/Rank/DropdownItems/InterestToggleList.tsx
  src/components/Rank/EducationRank/EducationRankItem/index.tsx
  src/components/Rank/EducationRank/EducationRankList/index.tsx
  src/components/Rank/EducationRank/index.tsx
  src/components/Rank/KewordRank/index.tsx
  src/components/Rank/PostRank/PostRankList/index.tsx
  src/components/Rank/PostRank/index.tsx
  src/components/Rank/SearchKeywordRank/SearchKeywordRankItem/index.tsx
  src/components/Rank/SearchKeywordRank/index.tsx
  src/components/SimilarEducationDetail/index.tsx
  src/components/SimilarEducationList/index.tsx
  src/components/UserForm/index.tsx
  src/components/UserForm/userFormData.ts
  src/constants/userForm/userFormData.ts
  src/features/rank/ageSlice.ts
  src/features/rank/agesSlice.ts
  src/features/rank/interestSlice.ts
  src/toolkit/store.ts
  src/type/rank.ts
  src/type/userForm.ts
Labels: Refactor, Question

#113 Hotfix/user의 age 값 조정
  public/data/rankingData.ts
  src/api/rank/readEducationInterestRank.ts
  src/api/rank/readKeywordAgeRank.ts
  src/api/rank/readPostRank.ts
  src/api/user/createUser.tsx
  src/components/Rank/DropdownItems/AgeDropDown.tsx
  src/components/Rank/EducationRank/index.tsx
  src/components/Rank/KewordRank/PieChart/index.tsx
  src/components/Rank/KewordRank/index.tsx
  src/components/Rank/PostRank/index.tsx
  src/components/Rank/SearchKeywordRank/SearchKeywordRankItem/index.tsx
  src/components/Rank/SearchKeywordRank/SearchKeywordRankList/index.tsx
  src/components/Rank/SearchKeywordRank/index.tsx
  src/components/UserForm/index.tsx
  src/constants/userForm/userFormData.ts
  src/features/rank/ageSlice.ts
  src/toolkit/store.ts
  src/type/rank.ts
  src/type/userForm.ts
Labels: Bug, Feature, Refactor

#114 Feature/홈페이지 시각화 UI 수정
  public/data/rankingData.ts
  public/images/chat.png
  public/images/group.png
  public/images/open-book.png
  src/components/Rank/DropdownItems/AgeDropDown.tsx
  src/components/Rank/DropdownItems/DropDown.tsx
  src/components/Rank/DropdownItems/InterestDropDown.tsx
  src/components/Rank/EducationRank/index.tsx
  src/components/Rank/KewordRank/PieChart/index.tsx
  src/components/Rank/KewordRank/index.tsx
  src/components/Rank/PostRank/index.tsx
  src/components/Rank/RankLoading/index.tsx
  src/components/Rank/RankNotFound/index.tsx
  src/components/Rank/RankServerError/index.tsx
  src/components/Rank/index.tsx
  src/constants/home/contents.ts
  src/features/rank/ageSlice.ts
  src/features/rank/interestSlice.ts
  src/scenes/Home/ContentItem/index.tsx
  src/scenes/Home/index.tsx
Labels: Feature, Refactor, Design
