Repository kimyoo04/seoul-competition-frontend, pull requests merged in 2023-04, with the labels that each got.

#3 chore: docker-compose.yml 수정, nginx Dockerfile 추가
  docker-compose.yml
  next/Dockerfile.dev
  next/Dockerfile.prod
  next/nginx/default.conf
  nginx/Dockerfile
  nginx/default.conf
Labels: documentation

#8 feature/디자인가이드_및_config_수정
  .github/convention.md
Labels: Docs

#9 feature/디자인가이드_및_config_수정
  .github/pull_request_template.md
Labels: Docs

#17 feature/디자인가이드 및 config 설정
  next/pages/_app.tsx
  next/src/components/Animation/ButtonWrapper.tsx
  next/styles/button.css
  next/styles/globals.css
  next/styles/textField.css
  next/tailwind.config.js
Labels: Feature, Design

#19 Feature/디자인가이드 및 config 설정
  next/pages/components/index.tsx
  next/styles/textField.css
Labels: Feature, Design

#20 feature/알림 UI 수정
  next/pages/_document.tsx
  next/pages/components/index.tsx
  next/src/components/Alert/Overlay.tsx
  next/src/components/Alert/index.tsx
Labels: Feature, Design

#22 feature/파일기반_라우팅_수정
  next/pages/board/[id].tsx
  next/pages/components/index.tsx
  next/pages/education/[id].tsx
Labels: Feature

#25 feature/교육 페이지
  next/package-lock.json
  next/package.json
  next/pages/educations/[id].tsx
  next/pages/educations/index.tsx
  next/public/data/educationData.ts
  next/src/api/axiosInstance.ts
  next/src/api/fetchEducation.ts
  next/src/features/education/educationSlice.ts
  next/src/scenes/Education/Card/index.tsx
  next/src/scenes/Education/index.tsx
  next/src/toolkit/store.ts
  next/src/type/education.ts
  next/tsconfig.json
Labels: Feature

#28 feature/게시판 무한 스크롤 적용
  next/pages/board/[id].tsx
  next/pages/educations/index.tsx
  next/pages/posts/[id].tsx
  next/pages/posts/index.tsx
  next/src/api/fetchEducations.ts
  next/src/api/fetchPostDetail.ts
  next/src/api/fetchPosts.ts
  next/src/features/education/educationSlice.ts
  next/src/features/post/postDetailSlice.ts
  next/src/features/post/postSlice.ts
  next/src/scenes/Board/index.tsx
  next/src/scenes/Educations/Card/index.tsx
  next/src/scenes/Educations/index.tsx
  next/src/scenes/Posts/Item/index.tsx
  next/src/scenes/Posts/index.tsx
  next/src/scenes/Posts/postDetail/index.tsx
  next/src/toolkit/store.ts
  next/src/type/education.ts
  next/src/type/post.ts
  next/src/type/postDetail.ts
Labels: Feature, Refactor

#32 Feature/디자인가이드 및 config 설정
  next/styles/button.css
Labels: Design

#35 Feature/교육 페이지
  next/next.config.js
  next/src/api/axiosInstance.ts
  next/src/api/fetchEducations.ts
  next/src/api/fetchPostDetail.ts
  next/src/api/fetchPosts.ts
  next/src/features/education/educationSlice.ts
  next/src/type/education.ts
Labels: Bug, Other

#38 Feature/검색 페이지 구현
  next/pages/search/index.tsx
  next/src/components/SearchBar/index.tsx
  next/src/features/search/searchSlice.ts
  next/src/layouts/OnePageLayout.tsx
  next/src/scenes/Search/SearchHistory/index.tsx
  next/src/scenes/Search/SearchRanking/index.tsx
  next/src/scenes/Search/index.tsx
  next/src/toolkit/store.ts
  next/src/type/search.ts
  next/styles/globals.css
  next/styles/textField.css
Labels: Feature, Design

#40 Feature/검색 페이지 구현
  next/src/components/SearchLink/index.tsx
  next/src/features/search/searchSlice.ts
  next/src/scenes/Search/ChooseCategory/ChooseButton.tsx
  next/src/scenes/Search/ChooseCategory/index.tsx
  next/src/scenes/Search/SearchBar/index.tsx
  next/src/scenes/Search/index.tsx
  next/src/toolkit/store.ts
  next/src/type/search.ts
Labels: Bug, Feature

#43 Feature/교육페이지 무한스크롤
  next/package-lock.json
  next/package.json
  next/pages/_app.tsx
  next/src/api/fetchEducations.ts
  next/src/components/Loading/index.tsx
  next/src/components/ScrollButton/index.tsx
  next/src/components/SearchLink/index.tsx
  next/src/features/education/educationSlice.ts
  next/src/layouts/Header/HeaderItem/SearchLink.tsx
  next/src/layouts/OnePageLayout.tsx
  next/src/scenes/Educations/Card/index.tsx
  next/src/scenes/Educations/index.tsx
  next/src/toolkit/store.ts
  next/src/type/education.ts
Labels: Bug, Feature, Design

#49 Feature/검색 페이지 구현
  src/api/fetchSearch.ts
  src/features/search/searchSlice.ts
  src/scenes/Search/ChooseCategory/index.tsx
  src/scenes/Search/SearchBar/index.tsx
  src/scenes/Search/SearchHistory/index.tsx
  src/scenes/Search/SearchRanking/index.tsx
  src/scenes/Search/SearchResult/index.tsx
  src/scenes/Search/index.tsx
  src/type/education.ts
  src/type/search.ts
Labels: Bug, Feature

#50 Feature/헤더 및 사이드바
  src/components/Animation/ButtonWrapper.tsx
  src/layouts/Header/HeaderItem/SearchLink.tsx
  src/layouts/Header/HeaderItem/SideToggle.tsx
  src/layouts/Header/Sidebar/index.tsx
  src/layouts/Header/index.tsx
Labels: Design

#52 Feature/헤더 및 사이드바
  src/components/FilterToggle/index.tsx
  src/components/Sidebar/Portal.tsx
  src/components/Sidebar/index.tsx
  src/layouts/Header/HeaderItem/Logo.tsx
  src/layouts/Header/HeaderItem/NavLinks.tsx
  src/layouts/Header/HeaderItem/SideToggle.tsx
  src/layouts/Header/Sidebar/NavLink.tsx
  src/layouts/Header/Sidebar/NavLinks.tsx
  src/layouts/Header/index.tsx
  src/layouts/MainLayout.tsx
  src/scenes/Educations/index.tsx
  src/scenes/Posts/index.tsx
Labels: Feature, Design

#53 Feature/검색 페이지 구현
  src/api/fetchEducations.ts
  src/api/fetchSearch.ts
  src/features/search/searchSlice.ts
  src/scenes/Educations/EducationItem/index.tsx
  src/scenes/Educations/index.tsx
  src/scenes/Search/ChooseCategory/ChooseButton.tsx
  src/scenes/Search/ChooseCategory/index.tsx
  src/scenes/Search/SearchBar/index.tsx
  src/scenes/Search/SearchKeywordsModal/index.tsx
  src/scenes/Search/SearchResult/SearchResultItem/header.tsx
  src/scenes/Search/SearchResult/index.tsx
  src/scenes/Search/index.tsx
  src/type/search.ts
Labels: Bug, Feature, Design

#55 Feature/교육 페이지 디테일 구현
  pages/educations/[id].tsx
  pages/posts/[id].tsx
  src/api/fetchEducationDetail.ts
  src/components/LocationMap/index.tsx
  src/layouts/Header/HeaderItem/SearchLink.tsx
  src/layouts/OnePageLayout.tsx
  src/scenes/Educations/EducationDetail/EducationDetailItem/content.tsx
  src/scenes/Educations/EducationDetail/index.tsx
  src/scenes/Educations/EducationItem/index.tsx
  src/scenes/Educations/index.tsx
  src/type/educationDetail.ts
Labels: Feature, Other

#59 Feature/검색 페이지 구현
  src/features/search/searchSlice.ts
  src/scenes/Search/ChooseCategory/index.tsx
  src/scenes/Search/SearchBar/index.tsx
  src/scenes/Search/SearchKeywordsModal/index.tsx
  src/scenes/Search/SearchResult/index.tsx
Labels: Bug, Design

#60 Feature/랜딩페이지 구현
  pages/index.tsx
  src/scenes/Home/CTABtn/index.tsx
  src/scenes/Home/ContentItem/contentData.ts
  src/scenes/Home/ContentItem/index.tsx
  src/scenes/Home/index.tsx
Labels: Feature, Design

#61 Feature/educations posts search 페이지 리펙토링
  src/api/fetchEducations.ts
  src/api/fetchPosts.ts
  src/api/fetchSearch.ts
  src/components/FilterToggle/index.tsx
  src/components/Header/ListPageHeader.tsx
  src/components/Loading/index.tsx
  src/scenes/Educations/index.tsx
  src/scenes/Posts/index.tsx
  src/scenes/Search/SearchResult/index.tsx
  src/type/education.ts
Labels: Bug, Refactor, Design

#62 Feature/헤더 및 사이드바
  src/components/FilterToggle/index.tsx
  src/components/SearchLink/index.tsx
  src/layouts/Header/HeaderItem/NavLinks.tsx
  src/layouts/Header/index.tsx
  src/scenes/Educations/index.tsx
  src/scenes/Posts/index.tsx
Labels: Feature, Refactor, Design
